name: Run tests

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
      - name: Debug Information
        run: python3 compiler/compiler.py tests/pl_programs/arrayBinarySearch.pl
        working-directory: src
      - name: Run tests
        run: pytest -v
        working-directory: src
