name: Run tests

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: install package
        run: sudo apt-get update && sudo apt-get install -y llvm clang gcc
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
      - name: Debug Information
        run: python3 -c "import sys; print(sys.path)"
        working-directory: src
      - name: Run tests
        run: pytest -v
        working-directory: src
