name: Run tests

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.1.0
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
      - name: Run tests
        run: pytest -v
        working-directory: src
      - name: Debug Information
        run: |
          echo "Working Directory: $(pwd)"
          echo "List of files in tests/pl_programs:"
          ls -la tests/pl_programs/
          echo "Python Version:"
          python --version
          echo "Installed Packages:"
          pip freeze
