name: Style the code

on: ["push", "pull_request"]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run Black
        run: black .

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[styler]"
          git config --global user.email "github-actions[styler]@example.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Apply Black formatting"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
